In [5]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
b = a.reshape(5,3)

In [11]:
a.shape

(15,)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
b.shape

(5, 3)

In [15]:
b.ndim

2

In [16]:
a.dtype.name

'int64'

In [19]:
b.size

15

In [20]:
type(a)

numpy.ndarray

In [21]:
x = np.array([1,2,3])

In [22]:
x

array([1, 2, 3])

In [23]:
x.dtype

dtype('int64')

In [24]:
y = np.array([(1,2,3), (4,5,6)])

In [25]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [29]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(0, 1, .1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [34]:
np.linspace(0, 5, 14)

array([ 0.        ,  0.38461538,  0.76923077,  1.15384615,  1.53846154,
        1.92307692,  2.30769231,  2.69230769,  3.07692308,  3.46153846,
        3.84615385,  4.23076923,  4.61538462,  5.        ])

In [35]:
from numpy import pi

In [36]:
pi

3.141592653589793

In [41]:
x = np.linspace(0, 2*pi, 10)

x

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [42]:
np.sin(x)

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [44]:
a - b

array([-3, -3, -3, -3, -3])

In [45]:
a + b

array([ 5,  7,  9, 11, 13])

In [46]:
b**2

array([16, 25, 36, 49, 64])

In [47]:
10 * np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495, -9.58924275])

In [55]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [62]:
b = np.random.random((2,3))
b

array([[ 0.16830517,  0.2788923 ,  0.41420033],
       [ 0.03982999,  0.49043424,  0.43283099]])

In [64]:
b += a
b

array([[ 6.16830517,  6.2788923 ,  6.41420033],
       [ 6.03982999,  6.49043424,  6.43283099]])

In [65]:
print (a.sum())

18


In [66]:
a.min()

3

In [69]:
b.max()

6.4904342395744656

In [70]:
b = np.arange(12).reshape(3,4)

In [71]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [73]:
b.sum(axis=1)

array([ 6, 22, 38])

In [74]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [75]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [76]:
a = np.arange(10)**3

In [77]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [79]:
a[5]

125

In [80]:
a[2:5]

array([ 8, 27, 64])

In [81]:
a[-1]

729

In [85]:
for row in b:
    print (row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [89]:
for row in b:
    for i in row:
        print (i, end=" ")
    print ("")

0 1 2 3 
4 5 6 7 
8 9 10 11 


In [90]:
for i in b.flat:
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11


In [91]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
b.shape = (6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [100]:
b.reshape(6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [101]:
b.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [102]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
b.resize(2,6)

In [104]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [105]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
b = np.array([(3,2,5), (14,15,16)])
b

array([[ 3,  2,  5],
       [14, 15, 16]])

In [107]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 3,  2,  5],
       [14, 15, 16]])

In [108]:
np.hstack((a,b))

array([[ 1,  2,  3,  3,  2,  5],
       [ 4,  5,  6, 14, 15, 16]])